author: "Victor Igor"
baseurl: ""
description: "Um blog sobre tudo que aprendo."
domain_name: "http://victorvoid.github.io/"
email: victor.0w3@hotmail.com
lang: pt-br
title: "Victor Igor | Blog"
url: "https://victorvoid.github.io"
keywords: "javascript, mongodb, victor igor gomes martins, victor igor, php, developer, programação, nodejs, victorvoid"
