# Site settings
title: Victor Igor - Front-end Engineer
description: "My name is Victor Igor, a front-end engineer from Brazil who lives in São Paulo."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://victorvoid.github.io" #http://localhost:3000

# User settings
username: victorvoid
user_title: Victor Igor - Front-end Engineer
email: victor.0w3@gmail.com
twitter_username: victorvoid_
github_username:  victorvoid
gplus_username:  victorigor0w3
disqus_username: victorvoid

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

articles:
  - name: Productivity in Learning with fluany
    date: 2017/09/29
    url: https://medium.com/@victorvoid/productivity-in-learning-with-fluany-fd808e1b6edc
  - name: Macros no JavaScript
    date: 2017/02/8
    url: https://medium.com/@victorvoid/macros-no-javascript-cdabe63ba35c
  - name: Conheça 6 tipos de polimorfismo
    date: 2017/01/16
    url: https://medium.com/@victorvoid/6-tipos-de-polimorfismo-7787080e8857
projects:
  - name: placeload.js
    description: The best way to create a placeholder layout effect. 🐨 
    url: https://github.com/victorvoid/placeload.js
    star: 144
    fork: 15
    language: JavaScript
  - name: vim-frontend
    description: A vim configured for Front-end Developers.⭐🔌
    url: https://github.com/victorvoid/vim-frontend
    star: 191
    fork: 12
    language: VimL
  - name: space-jekyll-template
    description: A simple spacemacs template on jekyll. 
    url: https://github.com/victorvoid/space-jekyll-template
    star: 222
    fork: 222
    language: CSS
  - name: react-button-loaders
    description: A collection of loading buttons easily customizable. 
    url: https://github.com/victorvoid/react-button-loaders
    star: 1
    fork: 1
    language: JavaScript
talks:
  - name: Everything is Composable
    description: Coders on Beer - 2018 - São Paulo
    url: https://www.slideshare.net/VictorCalangu/everything-is-composable
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
