# Site settings
title: Victor Igor
description: 'Gosta de JavaScript ? Sim ? Então já podemos ser amigos.'
url: 'http://victorvoid/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: victorvoid

author:
  name: 'Victor Igor'
  email: victor.0w3@hotmail.com
  twitter_username: victorvoid_
  facebook_username: victorcalangu
  github_username:  victorvoid

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:title/
markdown: kramdown
highlighter: rouge

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
