# Site settings
title: Victor Igor - Front-end Engineer
description: "Um blog sobre desenvolvimento web"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://victorvoid.github.io" #http://localhost:3000

# User settings
username: victor igor
user_title: Victor Igor - Desenvolvedor FrontEnd
email: victor.0w3@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Um blog pessoal que compartilha conhecimentos sobre Desenvolvimento web com foco em JavaScript.
twitter_username: victorvoid_
github_username:  victorvoid
gplus_username:  victorigor0w3
disqus_username: victorvoid

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

articles:
  - name: Productivity in Learning with fluany
    date: 2017/09/29
    url: https://medium.com/@victorvoid/productivity-in-learning-with-fluany-fd808e1b6edc
  - name: Macros no JavaScript
    date: 2017/02/8
    url: https://medium.com/@victorvoid/macros-no-javascript-cdabe63ba35c
  - name: Conheça 6 tipos de polimorfismo
    date: 2017/01/16
    url: https://medium.com/@victorvoid/6-tipos-de-polimorfismo-7787080e8857
projects:
  - name: fluany
    url: https://github.com/victorvoid/fluany
  - name: placeload.js
    url: https://github.com/victorvoid/placeload.js
  - name: vim-frontend
    url: https://github.com/victorvoid/vim-frontend
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
