# Site settings
description: "Um blog de anotações, resumos, e artigos de computação em geral."
baseurl: ""
url: "http://victorvoid.github.io" 
title: "Blog - Victor Igor"
# User settings
username: Victor Igor
user_description: Estudante de coisas da computação
user_title: "Anotações, resumos e artigos de computação em geral (ツ)"
email: victor.0w3@hotmail.com
twitter_username: vict0rvoid
github_username:  victorvoid
gplus_username:  VictorIgor0w3
disqus_username: victorvoid

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: Sobre Mim
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
